DELETE FROM PLATI;
DELETE FROM FACTURI;
DELETE FROM DETALII_CONTRACT;
DELETE FROM DECLARATII_FISCALE;
DELETE FROM CONTRACTE;
DELETE FROM VECTOR_FISCAL;
DELETE FROM DOCUMENTE_LEGALE;
DELETE FROM PUNCTE_LUCRU;
DELETE FROM PERSOANE_FIZICE;
DELETE FROM PERSOANE_JURIDICE;
DELETE FROM ANGAJATI;
DELETE FROM CLIENTI;
DELETE FROM TIPURI_DECLARATII;
DELETE FROM SERVICII;
DELETE FROM DEPARTAMENTE;
COMMIT;


DROP SEQUENCE SEQ_DEPARTAMENTE;
DROP SEQUENCE SEQ_SERVICII;
DROP SEQUENCE SEQ_TIPURI_DECLARATII;
DROP SEQUENCE SEQ_CLIENTI;
DROP SEQUENCE SEQ_ANGAJATI;
DROP SEQUENCE SEQ_VECTOR_FISCAL;
DROP SEQUENCE SEQ_CONTRACTE;
DROP SEQUENCE SEQ_FACTURI;
DROP SEQUENCE SEQ_PLATI;
DROP SEQUENCE SEQ_PUNCTE_LUCRU;
DROP SEQUENCE SEQ_DOCUMENTE_LEGALE;
DROP SEQUENCE SEQ_DECLARATII_FISCALE;


SELECT * FROM DECLARATII_FISCALE;

ALTER TABLE DECLARATII_FISCALE MODIFY stare_recipisa VARCHAR2(50);